parameters:
    dos.form.type.single_entity.class: DoS\ResourceBundle\Form\Type\EntityType
    dos.form.type.money.class: DoS\ResourceBundle\Form\Type\MoneyType
    dos.form.type.yaml.class: DoS\ResourceBundle\Form\Type\YamlType

    dos.listener.ajax_redirect.class: DoS\ResourceBundle\EventListener\AjaxRedirect
    dos.listener.sylius_translator_replace.class: DoS\ResourceBundle\EventListener\ReplaceSyliusTrans
    dos.listener.uuid_generator.class: DoS\ResourceBundle\EventListener\UuidGeneratorListener
    dos.listener.unique_state.class: DoS\ResourceBundle\EventListener\UniqueStateAbleListener

    dos.image_uploader.class: DoS\ResourceBundle\Uploader\ImageUploader
    dos.originator.class: DoS\ResourceBundle\Originator\Originator
    dos.templating.page_builder.class: DoS\ResourceBundle\Templating\PageBuilder
    dos.rest.view_handler.class: DoS\ResourceBundle\Rest\ViewHandler

    dos.class.twig.extension.intl: DoS\ResourceBundle\Twig\Extension\Intl
    dos.class.twig.extension.generic: DoS\ResourceBundle\Twig\Extension\Generic
    dos.class.twig.extension.image: DoS\ResourceBundle\Twig\Extension\Image
    dos.class.twig.extension.arrays: DoS\ResourceBundle\Twig\Extension\Arrays
    dos.class.twig.extension.currency: DoS\ResourceBundle\Twig\Extension\Currency
    dos.class.twig.extension.resource: DoS\ResourceBundle\Twig\Extension\Resource
    dos.class.twig.extension.page: DoS\ResourceBundle\Twig\Extension\Page
    dos.class.twig.extension.routing: DoS\ResourceBundle\Twig\Extension\Routing

services:
    dos.resource_controller.collection_provider:
        class: DoS\ResourceBundle\AclDecoratedResolver\ResourcesCollectionProvider
        decorates: sylius.resource_controller.resources_collection_provider
        arguments:
            - "@dos.resource_controller.collection_provider.inner"
            - "@sylius.authorization_identity_provider"
            - "@sylius.authorization_checker"

    dos.resource_controller.single_provider:
        class: DoS\ResourceBundle\AclDecoratedResolver\SingleResourceProvider
        decorates: sylius.resource_controller.single_resource_provider
        arguments:
            - "@dos.resource_controller.single_provider.inner"
            - "@security.authorization_checker"
            - "@sylius.authorization_checker"

    dos.grid.filters_applicator:
        class: DoS\ResourceBundle\AclDecoratedResolver\Grid\FiltersApplicator
        decorates: sylius.grid.filters_applicator
        arguments:
            - "@dos.grid.filters_applicator.inner"
            - "@sylius.registry.grid_filter"

    dos.grid.filter.resource_owner:
        class: DoS\ResourceBundle\AclDecoratedResolver\Grid\ResourceOwnerFilter
        tags:
            - { name: sylius.grid_filter, type: resource_owner }

    dos.rest.view_handler:
        parent: fos_rest.view_handler.default
        class: %dos.rest.view_handler.class%

    dos.listener.ajax_redirect:
        class: %dos.listener.ajax_redirect.class%
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: setJsonRedirection }

    dos.listener.sylius_translator_replace:
        class: %dos.listener.sylius_translator_replace.class%
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: replaceKeys }

    dos.listener.unique_state:
        class: %dos.listener.unique_state.class%
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    dos.form.type.entity:
        class: %dos.form.type.single_entity.class%
        arguments:
            - @doctrine
        tags:
            - { name: form.type, alias: dos_entity }

    dos.form.type.money:
        parent: sylius.form.type.money
        class: %dos.form.type.money.class%
        tags:
            - { name: form.type, alias: dos_money }

    dos.form.type.yaml:
        class: %dos.form.type.yaml.class%
        tags:
            - { name: form.type, alias: dos_yaml }

    dos.money:
        alias: sylius.templating.helper.money

    dos.listener.uuid_generator:
        class: %dos.listener.uuid_generator.class%
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    dos.upload_filesystem:
        class: Gaufrette\Filesystem
        factory_service: knp_gaufrette.filesystem_map
        factory_method: get
        arguments:
            - %dos.uploader.filesystem%

    dos.image_uploader:
        class: %dos.image_uploader.class%
        arguments:
            - @dos.upload_filesystem

    dos.originator:
        class: %dos.originator.class%
        arguments:
            - @doctrine

    dos.templating.page_builder:
        class: %dos.templating.page_builder.class%
        arguments:
            - @sylius.templating.helper.settings
        calls:
            - [setSeoPage, [@sonata.seo.page]]

    dos.twig.extension.intl:
        class: %dos.class.twig.extension.intl%
        arguments:
            - %dos.locale_traditional%
        tags:
            - { name: twig.extension }

    dos.twig.extension.generic:
        class: %dos.class.twig.extension.generic%
        arguments:
            - @service_container
        tags:
            - { name: twig.extension }

    dos.twig.extension.image:
        class: %dos.class.twig.extension.image%
        arguments:
            - @liip_imagine.cache.manager
            - @liip_imagine.filter.configuration
            - %dos.image_holder%
        tags:
            - { name: twig.extension }

    dos.twig.extension.arrays:
        class: %dos.class.twig.extension.arrays%
        tags:
            - { name: twig.extension }

    dos.twig.extension.currency:
        class: %dos.class.twig.extension.currency%
        tags:
            - { name: twig.extension }
        arguments:
            - @sylius.templating.helper.money
            - @sylius.templating.helper.settings

    dos.twig.extension.resource:
        parent: sylius.twig.extension.resource
        class: %dos.class.twig.extension.resource%
        tags:
            - { name: twig.extension }
            - { name: kernel.event_listener, event: kernel.request, method: fetchRequest }

    dos.twig.extension.page:
        class: %dos.class.twig.extension.page%
        strict: false
        arguments:
            - @dos.templating.page_builder
            - @sonata.seo.twig.extension
        calls:
            - [setContainer, [@service_container]]
        tags:
            - { name: twig.extension }

    dos.twig.extension.text:
     class: Twig_Extensions_Extension_Text
     tags:
         - { name: twig.extension }

    dos.twig.extension.routing:
     class: %dos.class.twig.extension.routing%
     arguments:
        - @router
        - @slugify
     tags:
         - { name: twig.extension }
