parameters:
    dos.form.type.single_entity.class: DoS\ResourceBundle\Form\Type\EntityType
    dos.form.type.money.class: DoS\ResourceBundle\Form\Type\MoneyType
    dos.form.type.yaml.class: DoS\ResourceBundle\Form\Type\YamlType

    dos.listener.uuid_generator.class: DoS\ResourceBundle\EventListener\UuidGeneratorListener
    dos.image_uploader.class: DoS\ResourceBundle\Uploader\ImageUploader
    dos.originator.class: Sylius\Component\Originator\Originator\Originator

services:
    dos.form.type.entity:
        class: %dos.form.type.single_entity.class%
        arguments:
            - @doctrine
        tags:
            - { name: form.type, alias: dos_entity }

    dos.form.type.money:
        parent: sylius.form.type.money
        class: %dos.form.type.money.class%
        tags:
            - { name: form.type, alias: dos_money }

    dos.form.type.yaml:
        class: %dos.form.type.yaml.class%
        tags:
            - { name: form.type, alias: dos_yaml }

    dos.money:
        alias: sylius.templating.helper.money

    dos.listener.uuid_generator:
        class: %dos.listener.uuid_generator.class%
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    dos.upload_filesystem:
        class: Gaufrette\Filesystem
        factory_service: knp_gaufrette.filesystem_map
        factory_method: get
        arguments:
            - %dos.uploader.filesystem%

    dos.image_uploader:
        class: %dos.image_uploader.class%
        arguments:
            - @dos.upload_filesystem

    dos.originator:
        class: %dos.originator.class%
        arguments:
            - @doctrine
